name: alohamora
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.3
  - mypy
  - pyqt
  - black
  - rapidfuzz
  - requests
  - pytest-cov
  - requests-mock
  - beautifulsoup4
  - flake8
  - pytest
  - python-dotenv
  - isort
